"""add last_match_id to player

Revision ID: 43193c95c383
Revises: 608a82b42d85
Create Date: 2024-12-01 18:53:04.203696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43193c95c383'
down_revision = '608a82b42d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_match_id', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('players_summoner_name_key', type_='unique')
        batch_op.drop_column('last_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('players_summoner_name_key', ['summoner_name'])
        batch_op.drop_column('last_match_id')

    # ### end Alembic commands ###
