"""Add opponent rank

Revision ID: 4e28e509af75
Revises: 04e751386fc7
Create Date: 2025-01-08 11:28:39.535218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e28e509af75'
down_revision = '04e751386fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_lane_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('opponent_lane_rank')

    # ### end Alembic commands ###
