"""added all time high/low, scores

Revision ID: 5f6141b65846
Revises: 1429f8b30f3c
Create Date: 2024-12-19 12:24:32.216683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6141b65846'
down_revision = '1429f8b30f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_time_highest_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('all_time_lowest_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('all_time_lowest_score')
        batch_op.drop_column('all_time_highest_score')

    # ### end Alembic commands ###
