"""Add most played role to player

Revision ID: 6233cb8046ef
Revises: c5d3af65fee6
Create Date: 2025-01-06 17:52:37.005707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6233cb8046ef'
down_revision = 'c5d3af65fee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('most_played_role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('most_played_role')

    # ### end Alembic commands ###
