"""Create player table

Revision ID: 93514bfc980a
Revises: 
Create Date: 2024-11-22 19:58:02.841715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93514bfc980a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summoner_name', sa.String(length=80), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summoner_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
