"""Add assigned_role to Match

Revision ID: c5d3af65fee6
Revises: 5f6141b65846
Create Date: 2025-01-06 17:12:57.472257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d3af65fee6'
down_revision = '5f6141b65846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('assigned_role')

    # ### end Alembic commands ###
