"""Add game_duration to Match

Revision ID: e9965940ba8e
Revises: 4e28e509af75
Create Date: 2025-01-08 15:04:13.060718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9965940ba8e'
down_revision = '4e28e509af75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('game_duration')

    # ### end Alembic commands ###
