"""Update player and add match

Revision ID: fab6a9b81da2
Revises: 93514bfc980a
Create Date: 2024-11-30 19:18:09.216925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab6a9b81da2'
down_revision = '93514bfc980a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summoner_name', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=10), nullable=False),
    sa.Column('puuid', sa.String(length=100), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puuid'),
    sa.UniqueConstraint('summoner_name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='_match_player_uc')
    )
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('summoner_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_pkey'),
    sa.UniqueConstraint('summoner_name', name='player_summoner_name_key')
    )
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###
